from .druidSpells import *
from .hunterSpells import *
from .mageSpells import *
from .paladinSpells import *
from .priestSpells import *
from .rogueSpells import *
from .shamanSpells import *
from .warlockSpells import *
from .warriorSpells import *
