from .druidWeapons import *
from .hunterWeapons import *
from .mageWeapons import *
from .paladinWeapons import *
from .priestWeapons import *
from .rogueWeapons import *
from .shamanWeapons import *
from .warlockWeapons import *
from .warriorWeapons import *
